/**
 * READ-ONLY on MySQL → writes to Supabase PostgreSQL.
 * Usage: node scripts/migrate-node.mjs
 * Env: scripts/.env.migration or MYSQL_* + SUPABASE_MIGRATION_URL
 */
import 'dotenv/config';
import mysql from 'mysql2/promise';
import pg from 'pg';
import { readFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationEnv = join(__dirname, '.env.migration');
if (existsSync(migrationEnv)) {
  for (const line of readFileSync(migrationEnv, 'utf8').split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i > 0) process.env[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
}

const MYSQL = {
  host: process.env.MYSQL_HOST,
  port: Number(process.env.MYSQL_PORT || 3306),
  user: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
};

const PG_URL = process.env.SUPABASE_MIGRATION_URL || process.env.SUPABASE_DB_URL;
/** Max rows per table (latest by PK / created_at). Set MIGRATE_ROW_LIMIT=0 for full copy. */
const ROW_LIMIT = Number(process.env.MIGRATE_ROW_LIMIT ?? 10);

function quoteIdent(name) {
  return `"${String(name).replace(/"/g, '""')}"`;
}

function mysqlColToPg(columnType, extra, columnKey) {
  const t = (columnType || 'text').toLowerCase();
  const ai = /auto_increment/i.test(extra || '');
  const id = ai && columnKey === 'PRI' ? ' GENERATED BY DEFAULT AS IDENTITY' : '';

  if (t.startsWith('tinyint(1)')) return ai ? 'INTEGER' + id : 'BOOLEAN';
  if (t.startsWith('tinyint')) return (ai ? 'INTEGER' : 'SMALLINT') + id;
  if (t.startsWith('smallint')) return (ai ? 'INTEGER' : 'SMALLINT') + id;
  if (t.startsWith('mediumint') || t.startsWith('int')) return 'INTEGER' + id;
  if (t.startsWith('bigint')) return 'BIGINT' + id;
  if (t.startsWith('decimal') || t.startsWith('numeric')) {
    const m = t.match(/\(([^)]+)\)/);
    return m ? `NUMERIC(${m[1]})` : 'NUMERIC';
  }
  if (t.startsWith('float')) return 'REAL';
  if (t.startsWith('double')) return 'DOUBLE PRECISION';
  if (t.startsWith('datetime') || t.startsWith('timestamp')) return 'TIMESTAMPTZ';
  if (t.startsWith('date')) return 'DATE';
  if (t.startsWith('time')) return 'TIME';
  if (t.startsWith('year')) return 'INTEGER';
  if (t.startsWith('json')) return ROW_LIMIT > 0 ? 'TEXT' : 'JSONB';
  if (t.startsWith('enum') || t.startsWith('set')) return 'TEXT';
  if (t.startsWith('blob') || t.startsWith('binary') || t.startsWith('varbinary')) return 'BYTEA';
  if (t.startsWith('char') || t.startsWith('varchar')) {
    const m = t.match(/\((\d+)\)/);
    if (m && Number(m[1]) <= 10485760) return `VARCHAR(${m[1]})`;
    return 'TEXT';
  }
  if (t.startsWith('text') || t.startsWith('longtext') || t.startsWith('mediumtext')) return 'TEXT';
  return 'TEXT';
}

function pickOrderColumn(cols) {
  const cn = (c) => c.column_name ?? c.COLUMN_NAME;
  const ck = (c) => c.column_key ?? c.COLUMN_KEY ?? '';
  const ex = (c) => c.extra ?? c.EXTRA ?? '';

  const priAi = cols.find((c) => ck(c) === 'PRI' && /auto_increment/i.test(ex(c)));
  if (priAi) return cn(priAi);

  const pri = cols.find((c) => ck(c) === 'PRI');
  if (pri) return cn(pri);

  for (const prefer of ['updated_at', 'created_at', 'timestamp', 'id']) {
    const f = cols.find((c) => cn(c) === prefer);
    if (f) return cn(f);
  }
  return cn(cols[0]);
}

async function main() {
  for (const k of ['host', 'user', 'password', 'database']) {
    if (!MYSQL[k]) throw new Error(`Missing MYSQL_${k.toUpperCase()}`);
  }
  if (!PG_URL) throw new Error('Missing SUPABASE_MIGRATION_URL');

  const mysqlConn = await mysql.createConnection(MYSQL);
  const pgPool = new pg.Pool({
    connectionString: PG_URL,
    ssl: process.env.PGSSL === 'disable' ? false : { rejectUnauthorized: false },
  });

  console.log('MySQL (read-only):', `${MYSQL.user}@${MYSQL.host}/${MYSQL.database}`);
  console.log('Target: Supabase PostgreSQL');
  if (ROW_LIMIT > 0) {
    console.log(`Mode: last ${ROW_LIMIT} rows per table (fast sample)\n`);
  } else {
    console.log('Mode: full table copy\n');
  }

  const [tables] = await mysqlConn.query(
    `SELECT table_name AS name FROM information_schema.tables
     WHERE table_schema = ? AND table_type = 'BASE TABLE'
     ORDER BY table_name`,
    [MYSQL.database]
  );

  console.log(`Tables to migrate: ${tables.length}\n`);

  const pgClient = await pgPool.connect();
  try {
    await pgClient.query('SET session_replication_role = replica');

    let done = 0;
    for (const { name } of tables) {
      done += 1;
      const tq = quoteIdent(name);
      try {

      const [cols] = await mysqlConn.query(
        `SELECT column_name, column_type, is_nullable, column_key, extra, column_default
         FROM information_schema.columns
         WHERE table_schema = ? AND table_name = ?
         ORDER BY ordinal_position`,
        [MYSQL.database, name]
      );

      const seen = new Set();
      const colDefs = [];
      const colNames = [];
      const jsonCols = new Set();
      for (const c of cols) {
        const cn = c.column_name ?? c.COLUMN_NAME;
        const ct = c.column_type ?? c.COLUMN_TYPE ?? 'text';
        const nullable = (c.is_nullable ?? c.IS_NULLABLE) === 'YES' ? '' : ' NOT NULL';
        const extra = c.extra ?? c.EXTRA ?? '';
        const columnKey = c.column_key ?? c.COLUMN_KEY ?? '';
        if (!cn || seen.has(cn)) continue;
        seen.add(cn);
        colNames.push(cn);
        if (ct.toLowerCase().startsWith('json')) jsonCols.add(cn);
        colDefs.push(`${quoteIdent(cn)} ${mysqlColToPg(ct, extra, columnKey)}${nullable}`);
      }

      const normalizeValue = (cn, v) => {
        if (v instanceof Date) {
          return Number.isNaN(v.getTime()) ? null : v.toISOString();
        }
        if (jsonCols.has(cn) && v != null) {
          if (typeof v === 'object') return v;
          if (typeof v === 'string') {
            if (v.trim() === '') return null;
            try {
              return JSON.parse(v);
            } catch {
              return null;
            }
          }
        }
        if (v === undefined) return null;
        return v;
      };

      await pgClient.query(`DROP TABLE IF EXISTS ${tq} CASCADE`);
      await pgClient.query(`CREATE TABLE ${tq} (${colDefs.join(', ')})`);

      const pgCols = colNames.map(quoteIdent).join(', ');
      let rows;

      if (ROW_LIMIT > 0) {
        const orderCol = pickOrderColumn(cols);
        const [result] = await mysqlConn.query(
          `SELECT * FROM \`${name}\` ORDER BY \`${orderCol}\` DESC LIMIT ?`,
          [ROW_LIMIT]
        );
        rows = result;
      } else {
        const [countRow] = await mysqlConn.query(`SELECT COUNT(*) AS c FROM \`${name}\``);
        const total = Number(countRow[0].c);
        if (total === 0) {
          console.log(`[${done}/${tables.length}] ${name} — empty`);
          continue;
        }
        rows = [];
        const batch = 500;
        for (let offset = 0; offset < total; offset += batch) {
          const [chunk] = await mysqlConn.query(
            `SELECT * FROM \`${name}\` LIMIT ? OFFSET ?`,
            [batch, offset]
          );
          rows.push(...chunk);
        }
      }

      if (!rows.length) {
        console.log(`[${done}/${tables.length}] ${name} — empty`);
        continue;
      }

      const placeholders = [];
      const values = [];
      rows.forEach((row, ri) => {
        const ph = colNames.map((_, ci) => `$${ri * colNames.length + ci + 1}`).join(', ');
        placeholders.push(`(${ph})`);
        colNames.forEach((cn) => {
          const raw = row[cn] ?? row[cn.toUpperCase?.()] ?? null;
          values.push(normalizeValue(cn, raw));
        });
      });

      await pgClient.query(
        `INSERT INTO ${tq} (${pgCols}) VALUES ${placeholders.join(', ')}`,
        values
      );

      const suffix = ROW_LIMIT > 0 ? ` (last ${ROW_LIMIT})` : '';
      console.log(`[${done}/${tables.length}] ${name} — ${rows.length} rows${suffix}`);
      } catch (err) {
        throw new Error(`${name}: ${err.message}`);
      }
    }

    await pgClient.query('SET session_replication_role = DEFAULT');
    console.log('\nMigration complete.');
  } finally {
    pgClient.release();
    await mysqlConn.end();
    await pgPool.end();
  }
}

main().catch((err) => {
  console.error('Migration failed:', err.message);
  process.exit(1);
});
